# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    include:
      - "*"
      
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: build_release
    displayName: "Build Release"
    
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: dotnet publish "$(Build.SourcesDirectory)/src/Sample/Sample.csproj" --output "$(Build.SourcesDirectory)/src/Sample/dist" --configuration Release
        displayName: "Build release"

      - task: ArchiveFiles@2
        displayName: "Zip release"
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)/src/Sample/dist"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/sample-app.zip"
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: "Publish zip"
        inputs:
          pathToPublish: "$(Build.ArtifactStagingDirectory)/sample-app.zip"
          artifactName: sample-app